df.shape 
df.head() 
df.info() 
df.describe() 
df.isnull().sum() 
Perguntas 
1. Quantas medições existem no dataset? (800,11)
2. Quantas cidades estão presentes na base? 10
3. Quais colunas representam poluentes atmosféricos? pm25, pm10 
4. Existem valores ausentes no dataset? Não

In [146]:
import pandas as pd

df = pd.read_csv('qualidade_ar_brasil.csv')

df.shape
df.head() 
df.info() 
df.describe() 
df.isnull().sum()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   data                 800 non-null    str
 1   cidade               800 non-null    str
 2   estado               800 non-null    str
 3   pm25                 800 non-null    float64
 4   pm10                 800 non-null    float64
 5   no2                  800 non-null    float64
 6   o3                   800 non-null    float64
 7   temperatura          800 non-null    float64
 8   umidade              800 non-null    float64
 9   indice_qualidade_ar  800 non-null    float64
 10  nivel_alerta         800 non-null    str
dtypes: float64(7), str(4)
memory usage: 68.9 KB

data                   0
cidade                 0
estado                 0
pm25                   0
pm10                   0
no2                    0
o3                     0
temperatura            0
umidade                0
indice_qualidade_ar    0
nivel_alerta           0
dtype: int64

In [147]:
import pandas as pd

df = pd.read_csv('qualidade_ar_brasil.csv')

df['cidade'].unique()

df.groupby('cidade') [['pm25','pm10','no2','o3']].mean()

                     pm25       pm10        no2         o3
cidade
Belo Horizonte  27.874026  48.409091  27.992208  30.141558
Brasília        31.351724  59.428736  29.926437  33.167816
Curitiba        25.339785  43.408602  26.151613  28.435484
Fortaleza       23.186250  44.662500  24.232500  34.176250
Manaus          26.271084  46.898795  22.566265  30.354217
Porto Alegre    26.798592  47.760563  27.959155  27.991549
Recife          23.416471  41.165882  24.320000  32.205882
Rio de Janeiro  27.825301  43.106024  30.925301  38.836145
Salvador        21.503896  39.102597  24.568831  34.274026
São Paulo       33.653125  56.256250  39.314062  34.878125

Liste as cidades presentes no dataset: 
'Brasília','Curitiba','Salvador','Belo Horizonte','Recife','Fortaleza','Rio de Janeiro','Porto Alegre','Manaus','São Paulo'
Calcule a média de poluição por cidade: 
1. Qual cidade apresenta maior média de PM2.5? 'São Paulo'
2. Qual cidade apresenta maior média de NO2? 'São Paulo'
3. Existe alguma cidade com níveis consistentemente mais altos de poluentes? São Paulo

In [148]:
import pandas as pd

df = pd.read_csv('qualidade_ar_brasil.csv')

df.groupby('cidade')['indice_qualidade_ar'].mean().sort_values(ascending=True)

cidade
Salvador          42.342857
Recife            43.198824
Curitiba          44.359140
Fortaleza         44.646250
Manaus            45.092771
Porto Alegre      46.898592
Belo Horizonte    48.344156
Rio de Janeiro    50.639759
Brasília          54.955172
São Paulo         59.345312
Name: indice_qualidade_ar, dtype: float64

Perguntas
1. Qual cidade apresenta pior qualidade média do ar? São Paulo

2. Qual cidade apresenta melhor qualidade do ar? Salvador

In [149]:
import pandas as pd

df = pd.read_csv('qualidade_ar_brasil.csv')

df_alerta = df[df['nivel_alerta'].isin(['Ruim','Muito Ruim'])]
df_alerta.head(20)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
235,2025-04-20,São Paulo,SP,33.7,73.7,57.2,34.3,25.9,61.1,70.8,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
402,2025-07-12,São Paulo,SP,43.1,64.6,35.4,50.1,23.4,74.6,70.0,Ruim
408,2025-07-15,São Paulo,SP,38.3,72.1,35.3,53.2,23.9,66.8,70.5,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
498,2025-08-22,Rio de Janeiro,RJ,44.5,58.9,41.7,45.8,26.1,81.9,70.2,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim

Perguntas
1. Quantos registros possuem alerta crítico? 14
2. Em quais cidades eles ocorrem com maior frequência? São Paulo

In [150]:
import pandas as pd

df = pd.read_csv('qualidade_ar_brasil.csv')

df.sort_values('indice_qualidade_ar',ascending=False).head(10)

,data,cidade,estado,pm25,pm10,no2,o3,temperatura,umidade,indice_qualidade_ar,nivel_alerta
488,2025-08-19,São Paulo,SP,55.2,78.8,55.0,45.3,20.3,80.3,86.3,Ruim
431,2025-07-27,São Paulo,SP,60.1,50.0,56.4,54.8,25.2,76.3,84.3,Ruim
410,2025-07-15,São Paulo,SP,42.4,87.6,44.6,40.2,21.2,74.7,76.5,Ruim
379,2025-07-03,São Paulo,SP,51.7,78.9,48.3,26.8,21.6,68.0,76.1,Ruim
358,2025-06-20,Belo Horizonte,MG,44.5,78.9,41.8,46.1,27.0,64.8,75.9,Ruim
548,2025-09-17,Brasília,DF,54.3,69.2,37.4,36.0,23.8,62.5,73.6,Ruim
347,2025-06-17,Brasília,DF,52.7,79.1,35.4,31.9,28.6,51.0,73.5,Ruim
319,2025-06-01,Rio de Janeiro,RJ,45.1,70.1,37.4,48.0,28.1,78.9,72.7,Ruim
411,2025-07-15,São Paulo,SP,35.8,91.6,41.6,36.7,22.4,79.9,71.8,Ruim
320,2025-06-02,Manaus,AM,53.6,79.5,25.2,36.2,31.7,74.9,71.6,Ruim

Perguntas
1. Qual foi o pior dia registrado? 19/08/2025
2. Em qual cidade ocorreu? São Paulo
3. Quais poluentes estavam mais altos nesse dia? pm10, pm25, no2

In [151]:
import pandas as pd

df = pd.read_csv('qualidade_ar_brasil.csv')

df['data'] = pd.to_datetime(df['data'])

df['mes'] = df['data'].dt.month

df.groupby('mes')['indice_qualidade_ar'].mean()

mes
1     44.852308
2     42.985714
3     46.675949
4     47.559259
5     47.107813
6     52.881034
7     51.293443
8     49.640000
9     49.923333
10    47.865385
11    46.861429
12    45.829333
Name: indice_qualidade_ar, dtype: float64

Perguntas
1. Em quais meses a qualidade do ar tende a ser pior? Junho
2. Existe algum padrão sazonal? Sim, Outono costuma ser pior

In [152]:
import pandas as pd

df = pd.read_csv('qualidade_ar_brasil.csv')

df[['temperatura','pm25','pm10','no2','o3']].corr()

             temperatura      pm25      pm10       no2        o3
temperatura     1.000000 -0.114987 -0.112821 -0.168689  0.160547
pm25           -0.114987  1.000000  0.253494  0.124651  0.022676
pm10           -0.112821  0.253494  1.000000  0.151211 -0.002501
no2            -0.168689  0.124651  0.151211  1.000000  0.048104
o3              0.160547  0.022676 -0.002501  0.048104  1.000000

1. Existe correlação entre temperatura e poluição?
2. Quais poluentes parecem mais relacionados entre si?